### ISSUE TITLE
[Expander mode] BD sound change if it's not the only one triggered at a time

### ISSUE THREAD

**Issue by gihaume** [HomoElectromagneticus/Yocto_808#20] opened 2019-04-13 07:24 UTC
Try to send a sequence to the Yocto in expander mode in which the BD sometimes is alone and sometimes is triggered at the same time as another instrument. Then keep only the BD volume turned on, you should hear that its sound changes depending if it's triggered alone or not.

Also it can be noted that the Accent slot can also be set up to be triggable by an external MIDI note but this won't produce any result, while will still impact the issue described above the same.

**Comment by gihaume** [comment] 2019-04-19 16:36
I have my unit and the one from someone else which does this, hence why I stated the issue to be universal... but still, anyone if you can just try on yours to confirm you still have it, please do it.

**Comment by rv0** [comment] 2019-06-10 16:01
I just tried to reproduce this.
Ableton Live Demo, 2 patterns:
- 4/4 kick on 120 BPM.
- Same, but with 16th CHH and OHH between the kicks, and 4/4 clap.

I turned down all volumes, couldn't hear a difference in the kick. Would record it, but I don't have an audio interface here. Can you provide some more info (recordings and steps to reproduce)?

**Comment by gihaume** [comment] 2019-06-10 18:36
As I understand you tried in two different times a pattern with the BD alone and a pattern with the BD never alone on absame step.

Try a same pattern with sometimes the BD alone on some steps and sometimes with another instrument on some same steps.

I can make/find a recording at some point.

**Comment by rv0** [comment] 2019-06-10 22:21
but i switch between a pattern with the BD alone and one with the BD not alone and I don't hear a difference. I'm not saying there isn't a difference, it's very much possible! But in my simple test there was no audible difference.

**Comment by HomoElectromagneticus** [comment] 2019-06-13 05:06
I'm not able to reproduce this bug either. A recording would help a lot, @gihaume.

**Comment by HomoElectromagneticus** [comment] 2020-01-22 04:20
Since there was no follow-up from @gihaume and others have not been able to reproduce this problem, I am closing this issue.

**Closed by HomoElectromagneticus** 2020-01-22 04:20 UTC
