### ISSUE TITLE
Slaving to external MIDI Transport messages, then going in Edit mode, stop from external and not sending any external tempo anymore and press Start button make the sequencer unable to be internally clocked anymore in Pattern Play mode.

### ISSUE THREAD

**Issue by gihaume** [HomoElectromagneticus/Yocto_808#19] opened 2019-03-02 18:51 UTC
Sorry for the long title.

It seems related to a behavior/feature? that when having slaved the sequencer transport from an external MIDI Clock with the MIDI Slave mode, the Edit mode becomes slaved to the external MIDI Clock and pressing Start, Stop and Start again doesn't reset to the beginning of the pattern but continue where it stopped, as if it was a MIDI Continue message.

Personally I can't see the benefit of this and if it's a feature, I can't see why it's not available when using the internal clock. So I would suggest to get rid of it as it can produce the simili bug mentionned in the title.

EDIT: even more annoying when having Edit mode becoming slaved to external MIDI Clock and pressing Start and Stop, then sending a Start message from an external source... it will also act as continue. So it's more like that in Edit mode while clock is being slaved to external MIDI clock, the Stop button will act as "pause".

**Comment by rv0** [comment] 2019-03-03 14:47
the latest changes make it so that the sync mode where it was last played from gets remembered

if you want to use internal sync in edit mode after you were using midi sync, go to Internal sync pattern play mode first and press play there.

**Comment by rv0** [comment] 2019-06-10 17:18
As for the issue that you can stop/start internally while synced to external Midi clock (in EDIT mode), added a commit in the fix_trig_roll branch to fix that.

**Comment by HomoElectromagneticus** [comment] 2019-06-13 05:34
Is this issue closed now? I never attempted to reproduce this but it looks like you've made some commits to this issue, @rv0.

**Comment by rv0** [comment] 2019-06-13 09:10
Looks like it
This issue describes 3 issues, the issue in @gihaume's "EDIT" I could not reproduce

**Comment by HomoElectromagneticus** [comment] 2019-06-14 02:56
Okay I will close this then, thanks. @gihaume, feel free to reach out if you're still running into problems.

**Closed by HomoElectromagneticus** 2019-06-14 02:56 UTC
